name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          gh pr review ${{ env.PR_NUMBER }} --approve
          gh pr merge ${{ env.PR_NUMBER }} --auto --squash
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
